#!/usr/bin/env bash

set -euo pipefail

source ~/.bashrc

git apply "/patches/v${VOL_VER}.patch" 2>/dev/null ||
    git apply "/patches/${VOL_VER}.patch"

upd

if [[ $# -ne 0 ]]; then
    /bin/bash -i /io/$@
else
    /bin/bash -i
fi

exit 0
