FROM kalilinux/kali-last-release:latest

ENV DEBIAN_FRONTEND noninteractive

RUN set -e 							&& \
    apt-get update 						&& \
    apt-get upgrade -yq 					&& \
    apt-get install -yq --no-install-recommends			\
    	apt-utils						\
	build-essential						\
	bpftool							\
	ca-certificates						\
	dwarfdump						\
	curl							\
	clang							\
	elfutils						\
	exa							\
	graphviz 						\
	graphviz-dev						\
	git							\
	golang-go						\
	kali-tools-forensics					\
	libc6-dev						\
	libsnappy-dev						\
	llvm							\
    	locales							\
	python3							\
	python3-dev						\
	python3-pip						\
	ripgrep							\
	strace							\
	vim-gtk3						\
	xz-utils						\
    	zsh							&& \
    python3 -m pip install --upgrade --no-cache-dir pip 	&& \
    usermod -s /bin/zsh root					&& \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' 	\
      /etc/locale.gen 						&& \
    dpkg-reconfigure --frontend=noninteractive locales 		&& \
    update-locale LANG=en_US.UTF-8 				&& \
    apt-get -y autoremove --purge 				&& \
    apt-get clean 						&& \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root
RUN set -exu 							&& \
    git clone --depth 1 https://github.com/vobst/dotfiles	&& \
    yes | ./dotfiles/scripts/install.sh

WORKDIR /opt/vol
RUN set -exu 							&& \
    git clone							\
        https://github.com/volatilityfoundation/volatility3.git && \
    cd volatility3						&& \
    git checkout a35afd4f343c10d7f8d1df2cb5eec8364c3dbd5a	&& \
    pip3 install -r requirements.txt				&& \
    yes | pip3 uninstall capstone				&& \
    pip3 install 						\
	jsonschema						\
	networkx						\
	"https://github.com/aquynh/capstone/archive/next.zip#egg=capstone&subdirectory=bindings/python" \
	pygraphviz

WORKDIR /opt/vol
RUN set -exu 							&& \
    git clone							\
        https://github.com/volatilityfoundation/community3 	&& \
    git clone							\
        https://github.com/volatilityfoundation/dwarf2json 	&& \
    cd dwarf2json						&& \
    go build

WORKDIR /opt
RUN set -exu 							&& \
    git clone							\
    https://github.com/Gui774ume/ebpfkit-monitor

WORKDIR /opt/vol/volatility3
RUN set -exu 							&& \
    mkdir -p volatility3/symbols/linux				&& \
    chmod +x volshell.py

WORKDIR /io
