FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

RUN set -e 							&& \
    apt-get update 						&& \
    apt-get upgrade -yq 					&& \
    apt-get install -yq --no-install-recommends			\
	build-essential						\
	ca-certificates						\
	dwarfdump						\
	curl							\
	clang							\
	elfutils						\
	graphviz 						\
	graphviz-dev						\
	git							\
	golang-go						\
	libssl-dev						\
	llvm							\
    	locales							\
	python3							\
	python3-dev						\
	python3-pip						\
	xz-utils						&& \
    python3 -m pip install --upgrade --no-cache-dir pip 	&& \
    apt-get -y autoremove --purge 				&& \
    apt-get clean 						&& \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/vol
RUN set -exu 							&& \
    git clone							\
        https://github.com/volatilityfoundation/volatility3.git && \
    cd volatility3						&& \
    git checkout a35afd4f343c10d7f8d1df2cb5eec8364c3dbd5a	&& \
    pip3 install -r requirements.txt				&& \
    yes | pip3 uninstall capstone				&& \
    pip3 install 						\
	jsonschema						\
	networkx						\
	"https://github.com/aquynh/capstone/archive/next.zip#egg=capstone&subdirectory=bindings/python" \
	pygraphviz

WORKDIR /opt/vol
RUN set -exu 							&& \
    git clone							\
        https://github.com/volatilityfoundation/dwarf2json 	&& \
    cd dwarf2json						&& \
    go build

WORKDIR /opt/vol/volatility3
RUN set -exu 							&& \
    mkdir -p volatility3/symbols/linux				&& \
    chmod +x volshell.py

WORKDIR /io
